import { ChildDataType } from "@/schemas/new-child-form-schema";
import { EmployeeRole, RegisterEmployeeDto } from "@/types/employee";

export const sampleChildrenData: ChildDataType[] = [
  {
    name_by_care_center: "Daniel A.",
    name_by_family: "Daniel",
    age: 6,
    gender: "male",
    found_date: new Date("2024-05-01"),
  },
  {
    name_by_care_center: "Mimi B.",
    name_by_family: "Mimi",
    age: 4,
    gender: "female",
    found_date: new Date("2024-03-15"),
  },
  {
    name_by_care_center: "Abel C.",
    name_by_family: "Abel",
    age: 7,
    gender: "male",
    found_date: new Date("2023-12-12"),
  },
  {
    name_by_care_center: "Sofia D.",
    name_by_family: "Sofia",
    age: 3,
    gender: "female",
    found_date: new Date("2024-01-28"),
  },
  {
    name_by_care_center: "Yonatan E.",
    name_by_family: "Yonatan",
    age: 5,
    gender: "male",
    found_date: new Date("2024-02-18"),
  },
  {
    name_by_care_center: "Hanna F.",
    name_by_family: "Hanna",
    age: 2,
    gender: "female",
    found_date: new Date("2024-06-01"),
  },
  {
    name_by_care_center: "Nahom G.",
    name_by_family: undefined,
    age: 6,
    gender: "male",
    found_date: new Date("2023-09-23"),
  },
  {
    name_by_care_center: "Ruth H.",
    name_by_family: "Ruth",
    age: null,
    gender: "female",
    found_date: new Date("2024-04-04"),
  },
  {
    name_by_care_center: "Kaleb I.",
    name_by_family: "Kaleb",
    age: 8,
    gender: "male",
    found_date: new Date("2024-07-05"),
  },
  {
    name_by_care_center: "Lily J.",
    name_by_family: undefined,
    age: 5,
    gender: "female",
    found_date: new Date("2024-06-11"),
  },
  {
    name_by_care_center: "Teddy K.",
    name_by_family: "Teddy",
    age: 4,
    gender: "male",
    found_date: new Date("2024-03-22"),
  },
  {
    name_by_care_center: "Betty L.",
    name_by_family: "Betty",
    age: 3,
    gender: "female",
    found_date: new Date("2024-02-10"),
  },
  {
    name_by_care_center: "Mekdes M.",
    name_by_family: "Mekdes",
    age: null,
    gender: "female",
    found_date: new Date("2023-11-01"),
  },
  {
    name_by_care_center: "Elias N.",
    name_by_family: "Elias",
    age: 9,
    gender: "male",
    found_date: new Date("2024-01-13"),
  },
  {
    name_by_care_center: "Selam O.",
    name_by_family: undefined,
    age: 6,
    gender: "female",
    found_date: new Date("2024-05-25"),
  },
  {
    name_by_care_center: "Brook P.",
    name_by_family: "Brook",
    age: 7,
    gender: "male",
    found_date: new Date("2024-06-14"),
  },
  {
    name_by_care_center: "Feven Q.",
    name_by_family: "Feven",
    age: 5,
    gender: "female",
    found_date: new Date("2023-10-19"),
  },
  {
    name_by_care_center: "Samuel R.",
    name_by_family: "Samuel",
    age: 4,
    gender: "male",
    found_date: new Date("2024-07-01"),
  },
  {
    name_by_care_center: "Sara S.",
    name_by_family: "Sara",
    age: 3,
    gender: "female",
    found_date: new Date("2024-07-10"),
  },
  {
    name_by_care_center: "Lidya T.",
    name_by_family: "Lidya",
    age: null,
    gender: "female",
    found_date: new Date("2024-04-29"),
  },
];

export const mockEmployeeData: RegisterEmployeeDto[] = [
  {
    cityIdNumber: "AA12345",
    firstName: "Alice",
    lastName: "Smith",
    email: "alice@example.com",
    phoneNumber: "+251911111111",
    role: EmployeeRole.BUREAU_MANAGER,
    OrganizationUnitId: 1,
    activeStatus: true,
  },
  {
    cityIdNumber: "AA12346",
    firstName: "Bob",
    lastName: "Johnson",
    email: "bob@example.com",
    phoneNumber: "+251922222222",
    role: EmployeeRole.DIRECTOR,
    OrganizationUnitId: 1,
    activeStatus: true,
  },
  {
    cityIdNumber: "AA12347",
    firstName: "Charlie",
    lastName: "Williams",
    email: "charlie@example.com",
    phoneNumber: "+251933333333",
    role: EmployeeRole.EXPERT,
    OrganizationUnitId: 2,
    activeStatus: true,
  },
  {
    cityIdNumber: "AA12348",
    firstName: "David",
    lastName: "Brown",
    email: "david@example.com",
    phoneNumber: "+251944444444",
    role: EmployeeRole.SOCIAL_WORKER,
    OrganizationUnitId: 2,
    activeStatus: true,
  },
  {
    cityIdNumber: "AA12349",
    firstName: "Eve",
    lastName: "Davis",
    email: "eve@example.com",
    phoneNumber: "+251955555555",
    role: EmployeeRole.FACILITATOR_OFFICER,
    OrganizationUnitId: 3,
    activeStatus: true,
  },
  {
    cityIdNumber: "AA12350",
    firstName: "Fiona",
    lastName: "Clark",
    email: "fiona@example.com",
    phoneNumber: "+251966666666",
    role: EmployeeRole.BUREAU_MANAGER,
    OrganizationUnitId: 1,
    activeStatus: true,
  },
  {
    cityIdNumber: "AA12351",
    firstName: "George",
    lastName: "Miller",
    email: "george@example.com",
    phoneNumber: "+251977777777",
    role: EmployeeRole.DIRECTOR,
    OrganizationUnitId: 1,
    activeStatus: true,
  },
  {
    cityIdNumber: "AA12352",
    firstName: "Hannah",
    lastName: "Moore",
    email: "hannah@example.com",
    phoneNumber: "+251988888888",
    role: EmployeeRole.EXPERT,
    OrganizationUnitId: 2,
    activeStatus: true,
  },
  {
    cityIdNumber: "AA12353",
    firstName: "Ian",
    lastName: "Taylor",
    email: "ian@example.com",
    phoneNumber: "+251999999999",
    role: EmployeeRole.SOCIAL_WORKER,
    OrganizationUnitId: 2,
    activeStatus: true,
  },
  {
    cityIdNumber: "AA12354",
    firstName: "Julia",
    lastName: "Anderson",
    email: "julia@example.com",
    phoneNumber: "+251910101010",
    role: EmployeeRole.FACILITATOR_OFFICER,
    OrganizationUnitId: 3,
    activeStatus: true,
  },
  {
    cityIdNumber: "AA12355",
    firstName: "Kevin",
    lastName: "Thomas",
    email: "kevin@example.com",
    phoneNumber: "+251911111112",
    role: EmployeeRole.BUREAU_MANAGER,
    OrganizationUnitId: 1,
    activeStatus: true,
  },
  {
    cityIdNumber: "AA12356",
    firstName: "Laura",
    lastName: "Jackson",
    email: "laura@example.com",
    phoneNumber: "+251922222223",
    role: EmployeeRole.DIRECTOR,
    OrganizationUnitId: 1,
    activeStatus: true,
  },
  {
    cityIdNumber: "AA12357",
    firstName: "Michael",
    lastName: "White",
    email: "michael@example.com",
    phoneNumber: "+251933333334",
    role: EmployeeRole.EXPERT,
    OrganizationUnitId: 2,
    activeStatus: true,
  },
  {
    cityIdNumber: "AA12358",
    firstName: "Nina",
    lastName: "Harris",
    email: "nina@example.com",
    phoneNumber: "+251944444445",
    role: EmployeeRole.SOCIAL_WORKER,
    OrganizationUnitId: 2,
    activeStatus: true,
  },
  {
    cityIdNumber: "AA12359",
    firstName: "Oscar",
    lastName: "Martin",
    email: "oscar@example.com",
    phoneNumber: "+251955555556",
    role: EmployeeRole.FACILITATOR_OFFICER,
    OrganizationUnitId: 3,
    activeStatus: true,
  },
  {
    cityIdNumber: "AA12360",
    firstName: "Paula",
    lastName: "Lee",
    email: "paula@example.com",
    phoneNumber: "+251966666667",
    role: EmployeeRole.BUREAU_MANAGER,
    OrganizationUnitId: 1,
    activeStatus: true,
  },
  {
    cityIdNumber: "AA12361",
    firstName: "Quentin",
    lastName: "Perez",
    email: "quentin@example.com",
    phoneNumber: "+251977777778",
    role: EmployeeRole.DIRECTOR,
    OrganizationUnitId: 1,
    activeStatus: true,
  },
  {
    cityIdNumber: "AA12362",
    firstName: "Rachel",
    lastName: "Young",
    email: "rachel@example.com",
    phoneNumber: "+251988888889",
    role: EmployeeRole.EXPERT,
    OrganizationUnitId: 2,
    activeStatus: true,
  },
  {
    cityIdNumber: "AA12363",
    firstName: "Sam",
    lastName: "King",
    email: "sam@example.com",
    phoneNumber: "+251999999990",
    role: EmployeeRole.SOCIAL_WORKER,
    OrganizationUnitId: 2,
    activeStatus: true,
  },
  {
    cityIdNumber: "AA12364",
    firstName: "Tina",
    lastName: "Scott",
    email: "tina@example.com",
    phoneNumber: "+251910101011",
    role: EmployeeRole.FACILITATOR_OFFICER,
    OrganizationUnitId: 3,
    activeStatus: true,
  },
  {
    cityIdNumber: "AA12365",
    firstName: "Uma",
    lastName: "Baker",
    email: "uma@example.com",
    phoneNumber: "+251910101012",
    role: EmployeeRole.BUREAU_MANAGER,
    OrganizationUnitId: 1,
    activeStatus: true,
  },
  {
    cityIdNumber: "AA12366",
    firstName: "Victor",
    lastName: "Carter",
    email: "victor@example.com",
    phoneNumber: "+251910101013",
    role: EmployeeRole.DIRECTOR,
    OrganizationUnitId: 1,
    activeStatus: true,
  },
  {
    cityIdNumber: "AA12367",
    firstName: "Wendy",
    lastName: "Evans",
    email: "wendy@example.com",
    phoneNumber: "+251910101014",
    role: EmployeeRole.EXPERT,
    OrganizationUnitId: 2,
    activeStatus: true,
  },
  {
    cityIdNumber: "AA12368",
    firstName: "Xander",
    lastName: "Foster",
    email: "xander@example.com",
    phoneNumber: "+251910101015",
    role: EmployeeRole.SOCIAL_WORKER,
    OrganizationUnitId: 2,
    activeStatus: true,
  },
  {
    cityIdNumber: "AA12369",
    firstName: "Yara",
    lastName: "Graham",
    email: "yara@example.com",
    phoneNumber: "+251910101016",
    role: EmployeeRole.FACILITATOR_OFFICER,
    OrganizationUnitId: 3,
    activeStatus: true,
  },
  {
    cityIdNumber: "AA12370",
    firstName: "Zane",
    lastName: "Hall",
    email: "zane@example.com",
    phoneNumber: "+251910101017",
    role: EmployeeRole.BUREAU_MANAGER,
    OrganizationUnitId: 1,
    activeStatus: true,
  },
  {
    cityIdNumber: "AA12371",
    firstName: "Ava",
    lastName: "Irwin",
    email: "ava@example.com",
    phoneNumber: "+251910101018",
    role: EmployeeRole.DIRECTOR,
    OrganizationUnitId: 1,
    activeStatus: true,
  },
  {
    cityIdNumber: "AA12372",
    firstName: "Ben",
    lastName: "James",
    email: "ben@example.com",
    phoneNumber: "+251910101019",
    role: EmployeeRole.EXPERT,
    OrganizationUnitId: 2,
    activeStatus: true,
  },
  {
    cityIdNumber: "AA12373",
    firstName: "Cara",
    lastName: "Klein",
    email: "cara@example.com",
    phoneNumber: "+251910101020",
    role: EmployeeRole.SOCIAL_WORKER,
    OrganizationUnitId: 2,
    activeStatus: true,
  },
  {
    cityIdNumber: "AA12374",
    firstName: "Derek",
    lastName: "Lopez",
    email: "derek@example.com",
    phoneNumber: "+251910101021",
    role: EmployeeRole.FACILITATOR_OFFICER,
    OrganizationUnitId: 3,
    activeStatus: true,
  },
  {
    cityIdNumber: "AA12375",
    firstName: "Ella",
    lastName: "Moore",
    email: "ella@example.com",
    phoneNumber: "+251910101022",
    role: EmployeeRole.BUREAU_MANAGER,
    OrganizationUnitId: 1,
    activeStatus: true,
  },
  {
    cityIdNumber: "AA12376",
    firstName: "Finn",
    lastName: "Nguyen",
    email: "finn@example.com",
    phoneNumber: "+251910101023",
    role: EmployeeRole.DIRECTOR,
    OrganizationUnitId: 1,
    activeStatus: true,
  },
  {
    cityIdNumber: "AA12377",
    firstName: "Gina",
    lastName: "Owens",
    email: "gina@example.com",
    phoneNumber: "+251910101024",
    role: EmployeeRole.EXPERT,
    OrganizationUnitId: 2,
    activeStatus: true,
  },
  {
    cityIdNumber: "AA12378",
    firstName: "Henry",
    lastName: "Patel",
    email: "henry@example.com",
    phoneNumber: "+251910101025",
    role: EmployeeRole.SOCIAL_WORKER,
    OrganizationUnitId: 2,
    activeStatus: true,
  },
  {
    cityIdNumber: "AA12379",
    firstName: "Isla",
    lastName: "Quinn",
    email: "isla@example.com",
    phoneNumber: "+251910101026",
    role: EmployeeRole.FACILITATOR_OFFICER,
    OrganizationUnitId: 3,
    activeStatus: true,
  },
  {
    cityIdNumber: "AA12380",
    firstName: "Jack",
    lastName: "Reed",
    email: "jack@example.com",
    phoneNumber: "+251910101027",
    role: EmployeeRole.BUREAU_MANAGER,
    OrganizationUnitId: 1,
    activeStatus: true,
  },
  {
    cityIdNumber: "AA12381",
    firstName: "Kara",
    lastName: "Stone",
    email: "kara@example.com",
    phoneNumber: "+251910101028",
    role: EmployeeRole.DIRECTOR,
    OrganizationUnitId: 1,
    activeStatus: true,
  },
  {
    cityIdNumber: "AA12382",
    firstName: "Liam",
    lastName: "Turner",
    email: "liam@example.com",
    phoneNumber: "+251910101029",
    role: EmployeeRole.EXPERT,
    OrganizationUnitId: 2,
    activeStatus: true,
  },
  {
    cityIdNumber: "AA12383",
    firstName: "Mona",
    lastName: "Vasquez",
    email: "mona@example.com",
    phoneNumber: "+251910101030",
    role: EmployeeRole.SOCIAL_WORKER,
    OrganizationUnitId: 2,
    activeStatus: true,
  },
  {
    cityIdNumber: "AA12384",
    firstName: "Noah",
    lastName: "Wright",
    email: "noah@example.com",
    phoneNumber: "+251910101031",
    role: EmployeeRole.FACILITATOR_OFFICER,
    OrganizationUnitId: 3,
    activeStatus: true,
  },
];
