/* eslint-disable no-console */
/**
 * Coordinates measured from `public/assets/templates/association-form.pdf`
 * using `pdfjs-dist`. The template is generated by `soffice --headless
 * --convert-to pdf` from the source `.docx` (templates/ልማት ህብረት ቅጽ.docx).
 *
 * Re-measure by running: `npx tsx scripts/inspect-pdf.ts`
 *
 * Coordinate system: PDF points. Origin = bottom-left of the page.
 * y values below are text baselines (i.e. the bottom of the glyphs).
 *
 * Template: A4 LANDSCAPE (842 x 595 pt).
 * Was: US Letter landscape (792 x 612 pt) — see commit history.
 *
 * All positions below were measured directly from the rendered PDF
 * (not converted from cm). The y-axis is the PDF bottom-left origin;
 * pre-printed labels in the .docx use the top-left origin, and
 * pdfjs-dist's getTextContent returns coordinates in the PDF
 * coordinate system.
 */

export const PAGE_WIDTH = 842;
export const PAGE_HEIGHT = 595;

/* ──────────────────── Header (page 1) ──────────────────── */

/* Line 1 (y=544.6): "የልማት ህብረቱ የሚገኝበት ክ/ከተማ: <subcity>  ወረዳ: <woreda>  ብሎክ: <block>" */
export const HEADER_LINE1_Y = 544.6;
export const HEADER_LINE1_HEIGHT = 18;
export const HEADER_SUBCITY_X = 117.8;
export const HEADER_SUBCITY_W = 75.9;
export const HEADER_WOREDA_X = 262.3;
export const HEADER_WOREDA_W = 55.9;
export const HEADER_BLOCK_X = 340.3;
export const HEADER_BLOCK_W = 75.9;

/* Line 2 (y=530.4): "የልማቱ ህብረት ስያሜ: <name>  የአባላት ብዛት: <count>" */
export const HEADER_LINE2_Y = 530.4;
export const HEADER_LINE2_HEIGHT = 18;
export const HEADER_NAME_X = 113.5;
export const HEADER_NAME_W = 75.9;
export const HEADER_COUNT_X = 363.5;
export const HEADER_COUNT_W = 75.9;

/* ──────────────────── Leadership column (page 1) ──────────────────── */
/* Pre-printed labels in the template use 9pt body, so all y values
   are 9pt text baselines.

   The "ሙሉ ስም" label starts at x=35.5; the writable blank it
   describes starts at x=67.2. The "ስልክ ቁጥር" label starts at
   x=35.5; the writable blank starts at x=74.6. We expose the
   writable blank's x as LEADERSHIP_LEFT_X so the data field map
   draws the dynamic text exactly over the underscore. */

export const LEADERSHIP_LEFT_X = 67.2;
export const LEADERSHIP_NAME_BLANK_W = 130.0;
export const LEADERSHIP_PHONE_BLANK_X = 74.6;
export const LEADERSHIP_PHONE_BLANK_W = 26.5;
export const LEADERSHIP_RIGHT_X = 197.0;

/* Leader blocks on page 1. The first block has a slightly different
   layout (no separate "ሙሉ ስም" label was rendered in the template),
   so for leader 1 the name and phone share a tighter pair. */
export const LEADER_NAME_Y = {
  1: 492.1,
  2: 451.0,
  3: 411.4,
  4: 371.7,
} as const;

export const LEADER_PHONE_Y = {
  1: 485.1,
  2: 444.0,
  3: 404.3,
  4: 364.6,
} as const;

/* Leader 5 lives at the top of page 2 (before rows 9 & 10) */
export const LEADER5_NAME_Y_P2 = 466.6;
export const LEADER5_PHONE_Y_P2 = 459.5;

export const LEADER_FIELD_HEIGHT = 14;

/* ──────────────────── Member grid ──────────────────── */
/* 3 groups side-by-side. Each group has 3 cells: number | name | phone.
   Pre-printed column headers ("ቡድን N", "ሙሉ ስም", "ስልክ ቁጥር")
   are at y=506.7. */

export const GRID_HEADER_Y = 506.7;
export const GRID_COL_HEADER_Y = 503.2;

/* Per-group x positions: number digit | name blank | phone blank.
   The pre-printed underscores in the template are sized to fit
   3-word Amharic names and +251 9X XXX XXXX phones at 7pt font. */
export const GROUP_NUMBER_X = { 1: 131.9, 2: 234.1, 3: 338.9 } as const;
export const GROUP_NUMBER_W = 14.0;

export const GROUP_NAME_X = { 1: 141.8, 2: 246.7, 3: 351.6 } as const;
export const GROUP_NAME_W = 104.0;

export const GROUP_PHONE_X = { 1: 190.0, 2: 294.9, 3: 399.8 } as const;
export const GROUP_PHONE_W = 64.0;

/* y baselines for each row's "N" digit.
   Template spacing: rows 1-8 are on page 1, rows 9-10 on page 2.
   The step between rows on page 1 is ~24.5 pt. */
export const ROW_BASELINE_Y = {
  1: 492.1,
  2: 467.6,
  3: 443.1,
  4: 418.6,
  5: 394.1,
  6: 369.7,
  7: 345.1,
  8: 320.6,
  9: 548.8, /* page 2 */
  10: 517.7, /* page 2 */
} as const;

export const ROW_HEIGHT = 25;

/* ──────────────────── Page 2 bottom section ──────────────────── */

/* The data-collector line is ABOVE the approver line in the
   template. y=436.9 for data-collector (the higher line),
   y=408.5 for approver (the lower line). */
export const SECTION_DATA_COLLECTOR_Y = 436.9;
export const SECTION_DATA_COLLECTOR_NAME_X = 85.2;
export const SECTION_DATA_COLLECTOR_NAME_W = 70.0;
export const SECTION_DATA_COLLECTOR_SIG_X = 170.0;
export const SECTION_DATA_COLLECTOR_SIG_W = 50.0;
export const SECTION_DATA_COLLECTOR_DATE_X = 226.9;
export const SECTION_DATA_COLLECTOR_DATE_W = 84.0;

/* Approver line (lower on the page, smaller y) */
export const SECTION_APPROVER_Y = 408.5;
export const SECTION_APPROVER_NAME_X = 85.2;
export const SECTION_APPROVER_NAME_W = 70.0;
export const SECTION_APPROVER_SIG_X = 170.0;
export const SECTION_APPROVER_SIG_W = 50.0;
export const SECTION_APPROVER_DATE_X = 226.9;
export const SECTION_APPROVER_DATE_W = 84.0;

export const SECTION_FIELD_HEIGHT = 14;

/* ──────────────────── Signature image slots ──────────────────── */
/* These overlay the signature blanks on the right of each bottom-section line. */

export const SIGNATURE_ENTRY_SLOT = {
  page: 2 as const,
  x: 170.0,
  y: SECTION_DATA_COLLECTOR_Y - SECTION_FIELD_HEIGHT + 2,
  width: 50.0 - 4,
  height: SECTION_FIELD_HEIGHT - 4,
};

export const SIGNATURE_APPROVAL_SLOT = {
  page: 2 as const,
  x: 170.0,
  y: SECTION_APPROVER_Y - SECTION_FIELD_HEIGHT + 2,
  width: 50.0 - 4,
  height: SECTION_FIELD_HEIGHT - 4,
};
