/* eslint-disable no-console */
/**
 * Coordinates measured from `public/assets/templates/association-form.pdf`.
 * The template is generated by `soffice --headless --convert-to pdf` from
 * the source `.docx` (templates/ልማት ህብረት ቅጽ.docx).
 *
 * Re-measure by running: `npx tsx scripts/inspect-pdf.ts`
 *
 * Coordinate system: PDF points. Origin = bottom-left of the page.
 * y values below are text baselines (i.e. the bottom of the glyphs).
 *
 * Template: A4 LANDSCAPE (842 x 595 pt).
 * Was: US Letter landscape (792 x 612 pt) — see commit history.
 */

export const PAGE_WIDTH = 842;
export const PAGE_HEIGHT = 595;

/* ──────────────────── Header (page 1) ──────────────────── */

/* Line 1: "የልማት ህብረቱ የሚገኝበት ክ/ከተማ: <subcity>   ወረዳ: <woreda>   ብሎክ: <block>" */
export const HEADER_LINE1_Y = 555.6;
export const HEADER_LINE1_HEIGHT = 17;
export const HEADER_SUBCITY_X = 170.1;
export const HEADER_SUBCITY_W = 255.1;
export const HEADER_WOREDA_X = 453.5;
export const HEADER_WOREDA_W = 113.4;
export const HEADER_BLOCK_X = 623.6;
export const HEADER_BLOCK_W = 198.4;

/* Line 2: "የልማቱ ህብረት ስያሜ: <name>   የአባላት ብዛት: <count>" */
export const HEADER_LINE2_Y = 527.2;
export const HEADER_LINE2_HEIGHT = 17;
export const HEADER_NAME_X = 170.1;
export const HEADER_NAME_W = 283.5;
export const HEADER_COUNT_X = 453.5;
export const HEADER_COUNT_W = 255.1;

/* ──────────────────── Leadership column (page 1) ──────────────────── */
/* Left column spans x=14..184. Fields are full-width. */

export const LEADERSHIP_LEFT_X = 14.2;
export const LEADERSHIP_RIGHT_X = 184.3;

/* y of each leader's "ሙሉ ስም" label baseline */
export const LEADER_NAME_Y = {
  1: 450.7,
  2: 360.0,
  3: 280.6,
  4: 201.3,
  /* Leader 5 fields are at the top of page 2 */
} as const;

/* y of each leader's "ስልክ ቁጥር" label baseline */
export const LEADER_PHONE_Y = {
  1: 436.5,
  2: 345.8,
  3: 266.5,
  4: 187.1,
  /* Leader 5 phone is on page 2 */
} as const;

/* Leader 5 lives at the top of page 2 (before rows 9 & 10) */
export const LEADER5_NAME_Y_P2 = 411.0;
export const LEADER5_PHONE_Y_P2 = 377.0;

export const LEADER_FIELD_HEIGHT = 14;

/* ──────────────────── Member grid ──────────────────── */
/* 3 groups side-by-side. Within each group: ተ.ቁ | ሙሉ ስም | ስልክ ቁጥር */

/* Group starting x (left edge of "ተ.ቁ" column) */
export const GROUP_NUMBER_X = { 1: 198.4, 2: 408.2, 3: 618.0 } as const;
export const GROUP_NUMBER_W = 28.3;

/* Within each group, name column starts after number column */
export const GROUP_NAME_X = { 1: 226.7, 2: 436.5, 3: 646.3 } as const;
export const GROUP_NAME_W = { 1: 96.4, 2: 96.4, 3: 96.4 } as const;

export const GROUP_PHONE_X = { 1: 323.1, 2: 532.9, 3: 742.7 } as const;
export const GROUP_PHONE_W = { 1: 85.1, 2: 85.1, 3: 85.1 } as const;

/* y of each row's "N" digit (baseline) */
export const ROW_BASELINE_Y = {
  1: 442.2,
  2: 393.2,
  3: 344.2,
  4: 295.2,
  5: 246.2,
  6: 197.2,
  7: 148.2,
  8: 99.2,
  9: 555.6, /* page 2 */
  10: 493.2, /* page 2 */
} as const;

export const ROW_HEIGHT = 49;

/* ──────────────────── Page 2 bottom section ──────────────────── */

/* Data collector line */
export const SECTION_DATA_COLLECTOR_Y = 340.2;
export const SECTION_DATA_COLLECTOR_NAME_X = 113.4;
export const SECTION_DATA_COLLECTOR_NAME_W = 141.7;
export const SECTION_DATA_COLLECTOR_SIG_X = 255.1;
export const SECTION_DATA_COLLECTOR_SIG_W = 113.4;
export const SECTION_DATA_COLLECTOR_DATE_X = 368.5;
export const SECTION_DATA_COLLECTOR_DATE_W = 198.4;

/* Approver line (same column structure) */
export const SECTION_APPROVER_Y = 283.5;
export const SECTION_APPROVER_NAME_X = 113.4;
export const SECTION_APPROVER_NAME_W = 141.7;
export const SECTION_APPROVER_SIG_X = 255.1;
export const SECTION_APPROVER_SIG_W = 113.4;
export const SECTION_APPROVER_DATE_X = 368.5;
export const SECTION_APPROVER_DATE_W = 198.4;

export const SECTION_FIELD_HEIGHT = 14;

/* ──────────────────── Signature image slots ──────────────────── */
/* These overlay the signature blanks on the right of each bottom-section line. */

export const SIGNATURE_ENTRY_SLOT = {
  page: 2 as const,
  x: 260.8,
  y: SECTION_DATA_COLLECTOR_Y - SECTION_FIELD_HEIGHT + 2,
  width: 102.1,
  height: SECTION_FIELD_HEIGHT - 4,
};

export const SIGNATURE_APPROVAL_SLOT = {
  page: 2 as const,
  x: 260.8,
  y: SECTION_APPROVER_Y - SECTION_FIELD_HEIGHT + 2,
  width: 102.1,
  height: SECTION_FIELD_HEIGHT - 4,
};
